# Imagen base de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos del proyecto al contenedor
COPY . /app

# Instalar dependencias del sistema (si necesitas paquetes específicos)
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*

# Crear y activar un entorno virtual en el contenedor
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Instalar las dependencias del proyecto
RUN pip install --upgrade pip
RUN pip install -r requirements.txt -r requirements-dev.txt -r requirements-test.txt

# Puerto por defecto (si estás corriendo la API desde aquí)
EXPOSE 8000

# Comando por defecto para acceder al contenedor
CMD ["bash"]
